FROM node:18

WORKDIR /usr/src/app

# Copy package.json and package-lock.json and install dependencies
COPY package.json package-lock.json* ./
RUN npm install

# Copy app code
COPY . .

EXPOSE 3000

CMD ["npm", "start"]
